CREATE TABLE divisions (
	id INT NOT NULL AUTO_INCREMENT,
	division_name VARCHAR(100) NOT NULL UNIQUE,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);