CREATE TABLE employees (
	id INT NOT NULL AUTO_INCREMENT,
	person_id INT NOT NULL,
	from_date DATETIME NOT NULL,
	to_date DATETIME NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);