CREATE TABLE events (
	id INT NOT NULL AUTO_INCREMENT,
	ref_num VARCHAR(15) NOT NULL UNIQUE,
	event_name VARCHAR(100) NOT NULL,
	place VARCHAR(100) NOT NULL,
	from_date DATETIME NOT NULL,
	to_date DATETIME NOT NULL,
	printing TINYINT(1) NOT NULL,
	usb TINYINT(1) NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE event_photobooths (
	id INT NOT NULL AUTO_INCREMENT,
	photobooth_id INT NOT NULL,
	event_id INT NOT NULL,
	backdrop INT NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE event_employees (
	id INT NOT NULL AUTO_INCREMENT,
	employee_id INT NOT NULL,
	event_id INT NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE photobooths (
	id INT NOT NULL AUTO_INCREMENT,
	photobooth_name VARCHAR(100) NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE backdrops (
	id INT NOT NULL AUTO_INCREMENT,
	backdrop_name VARCHAR(100) NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE themas (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);