CREATE TABLE events (
	id INT NOT NULL AUTO_INCREMENT,
	ref_num VARCHAR(15) NOT NULL UNIQUE,
	division_id INT NOT NULL,
	name VARCHAR(100) NOT NULL,
	venue VARCHAR(100) NOT NULL,
	from_date DATETIME NOT NULL,
	to_date DATETIME NOT NULL,
	printing TINYINT(1) NOT NULL,
	usb TINYINT(1) NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	deleted_at TIMESTAMP NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE event_photobooths (
	id INT NOT NULL AUTO_INCREMENT,
	photobooth_id INT NOT NULL,
	event_id INT NOT NULL,
	division_backdrop_id INT NOT NULL,
	photo_layer TINYINT(1) NOT NULL,
	touch_to_start TINYINT(1) NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	deleted_at TIMESTAMP NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE event_props (
	id INT NOT NULL AUTO_INCREMENT,
	event_id INT NOT NULL,
	division_prop_id INT NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	deleted_at TIMESTAMP NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE event_attendees (
	id INT NOT NULL AUTO_INCREMENT,
	employee_id INT NOT NULL,
	event_id INT NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	deleted_at TIMESTAMP NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
