CREATE TABLE files (
	id INT NOT NULL AUTO_INCREMENT,
	location VARCHAR(200) NOT NULL UNIQUE,
	name VARCHAR(200) NOT NULL,
	client_name VARCHAR(200) NOT NULL,
	extension VARCHAR(10) NOT NULL,
	type VARCHAR(10) NOT NULL,
	description VARCHAR(1000) NULL,
	size INT NOT NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	deleted_at TIMESTAMP NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);