CREATE TABLE user_logs (
	id INT NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	log_type INT NOT NULL,
	log_msg VARCHAR(200) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	log_type INT NOT NULL,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	permission INT NOT NULL,
	token VARCHAR(255) NOT NULL,
	person_id INT NOT NULL,
	last_login DATETIME NULL,
	last_activity DATETIME NULL,
	first_fail_password DATETIME NULL,
	fail_counter TINYINT(1) NULL,
	banned TINYINT(1) NULL,
	last_edit_by INT NOT NULL,
	created_by INT NOT NULL,
	deleted_at TIMESTAMP NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE log_types (
	id INT NOT NULL AUTO_INCREMENT,
	type_name VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
);
-- permissions